export const LOCATION = [
  'Kab. Tangerang',
  'Jakarta Pusat',
  'Malang',
  'Yogyakarta',
  'Kab. Sidoarjo',
  'Makassar',
  'Dilayani Tokopedia',
  'Jakarta Utara',
  'Jakarta Timur',
  'Kab. Bekasi',
  'Jakarta Selatan',
  'Kab. Bogor',
  'Surabaya',
  'Semarang',
  'Jakarta Barat',
  'Tangerang Selatan',
  'Tangerang',
  'Kab. Bantul',
  'Depok',
  'Kab. Karawang',
  'Bandung',
  'Kab. Sragen',
  'Kab. Sukoharjo',
  'Bekasi',
  'Cimahi',
  'Kab. Kudus',
  'Denpasar',
  'Medan',
  'Kab. Bandung',
  'Kab. Purbalingga',
  'Palembang',
  'Batam',
  'Kab. Wonogiri',
  'Kab. Sleman',
  'Surakarta',
  'Kab. Bandung Barat',
  'Kab. Garut',
  'Bogor',
  'Pekanbaru',
  'Pangkal Pinang',
  'Pontianak',
  'Kab. Banjarnegara',
  'Tokopedia NOW!',
  'Kab. Pasuruan',
  'Salatiga',
  'Kab. Tasikmalaya',
  'Kab. Cilacap',
  'Kab. Badung',
  'Kab. Cianjur',
  'Padang',
  'Kab. Banyumas',
  'Bandar Lampung',
  'Kab. Sumedang',
  'Kab. Banyuwangi',
  'Kab. Karanganyar',
  'Kab. Cirebon',
  'Kab. Pacitan',
  'Kab. Malang',
  'Sukabumi',
  'Manado',
  'Kab. Semarang',
  'Kab. Serang',
  'Kab. Pandeglang',
  'Kab. Sukabumi',
  'Kab. Lamongan',
  'Batu',
  'Kab. Kediri',
  'Samarinda',
  'Cirebon',
  'Kab. Gresik',
  'Pekalongan',
  'Kab. Demak',
  'Kab. Jember',
  'Tegal',
  'Kab. Pekalongan',
  'Kab. Subang',
  'Kab. Ponorogo',
  'Kab. Sumenep',
  'Kab. Tegal',
  'Magelang',
  'Kab. Rembang',
  'Balikpapan',
  'Serang',
  'Kab. Klaten',
  'Kab. Jepara',
  'Kab. Bangkalan',
  'Tasikmalaya',
  'Kab. Gianyar',
  'Kab. Purwakarta',
  'Kab.Ciamis',
  'Madiun',
  'Kab. Kendal',
  'Blitar',
  'Kab. Nganjuk',
  'Kediri',
  'Cilegon',
  'Kab. Kuningan',
  'Banjarmasin',
  'Kab. Magelang',
  'Kab. Mojokerto',
  'Banjar',
  'Kab. Majalengka',
  'Kab. Bojonegoro',
  'Kab. Kapuas',
  'Kab. Lebak',
  'Kab. Kebumen',
  'Kab. Deli Serdang',
  'Banjarbaru',
  'Kab. Karimun',
  'Tanjung Pinang',
  'Kab. Brebes',
  'Kab. Lombok Barat',
  'Pasuruan',
  'Kab. Indramayu',
  'Singkawang',
  'Jambi',
  'Kab. Banjar',
  'Palu',
  'Kab. Grobogan',
  'Kab. Gunungkidul',
  'Kab. Pringsewu',
  'Kab. Temanggung',
  'Kab. Ngawi',
  'Kab. Buleleng',
  'Kab. Blora',
  'Kab. Sambas',
  'Kab. Pemalang',
  'Kab. Trenggalek',
  'Kab. Rokan Hulu',
  'Kab. Pati',
  'Kab. Kulon Progo',
  'Kab. Magetan',
  'Ambon',
  'Kab. Maros',
  'Kab. Tulungagung',
  'Probolinggo',
  'Kab. Boyolali',
  'Kab. Tanah Laut',
  'Palangkaraya',
  'Kab. Banyuasin',
  'Kab. Madiun',
  'Kab. Jombang',
  'Mataram',
  'Lubuk Linggau',
  'Kab. Lampung Tengah',
  'Mojokerto',
  'Kab. Karangasem',
  'Kab. Lampung Selatan',
  'Padang Panjang',
  'Kab. Tuban',
  'Kab. Kuantan Singingi',
  'Kab. Penukal Abab Lematang Ilir',
  'Kab. Paser',
  'Kab. Belitung',
  'Kab. Kutai Kartanegara',
  'Kupang',
  'Kab. Wonosobo',
  'Sabang',
  'Binjai',
  'Kab. Tabanan',
  'Kab. Sidenreng Rappang',
  'Kendari',
  'Metro',
  'Kab. Lombok Utara',
  'Kab. Muara Enim',
  'Kab. Pangandaran',
  'Kab. Lumajang',
  'Kab. Melawi',
  'Kab. Kubu Raya',
  'Bengkulu',
  'Kab. Blitar',
  'Kab. Jembrana',
  'Kab. Situbondo',
  'Kab. Ogan Komering Ulu Timur',
  'Kab. Kampar',
  'Kab. Probolinggo',
  'Kab. Lombok Tengah',
  'Kab. Maluku Tengah',
  'Sorong',
  'Kab. Purworejo',
  'Kab. Lampung Barat',
  'Kab. Tapanuli Utara',
  'Kab. Bondowoso',
  'Kab. Kutai Barat',
  'Prabumulih',
  'Payakumbuh',
  'Solok',
  'Kab. Langkat',
  'Kab. Batang',
];
