export const PENDAFTARAN_STAFF_PAGES = [
  {
    id: 1,
    name: 'General',
    pertanyaan: [
      'name',
      'nrp',
      'departemen',
      'fakultas',
      'no_telp',
      'id_line',
      'pengetahuan',
      'motivasi',
      'inovasi',
      'divisi_1',
      'divisi_2',
      'alasan_divisi_1',
      'alasan_divisi_2',
      'link_portofolio',
    ],
  },
  {
    id: 2,
    name: 'Upload Bukti',
    pertanyaan: [
      'bukti_instagram',
      'bukti_twitter',
      'bukti_tiktok',
      'bukti_youtube',
      'bukti_feeds',
      'bukti_twibbon',
    ],
  },
  { id: 3, name: 'Divisi 1' },
  { id: 4, name: 'Divisi 2' },
];

export const PENDAFTARAN_STAFF_DIVISIONS = [
  { id: 1, name: 'Creative Documentation' },
  { id: 2, name: 'Social Media Management' },
  { id: 3, name: 'Consumption' },
  { id: 4, name: 'Data Management' },
  { id: 5, name: 'Decoration' },
  { id: 6, name: 'Design Creative' },
  { id: 7, name: 'Equipment' },
  { id: 8, name: 'Event' },
  { id: 9, name: 'Fundraising' },
  { id: 10, name: 'Sponsorship' },
  { id: 11, name: 'Medical' },
  { id: 12, name: 'External' },
  { id: 13, name: 'UKM Coordinator' },
  { id: 14, name: 'Secure & License' },
  { id: 15, name: 'Web Development' },
];
